#  Enterprise-Grade SQL LLM Pipeline
**End-to-end Supervised Fine-Tuning, Direct Preference Optimization, and vLLM Serving**

This notebook executes a complete MLOps pipeline to train and deploy Llama 3.1 8B for strict, deterministic SQL code generation on a free 15GB GPU.

### **Pipeline Architecture:**
*   **Phase 1: Data Engineering.** Ingesting 75k rows, enforcing ChatML formatting, and engineering a heuristic-based dataset of "bad" SQL for alignment.
*   **Phase 2: Base Model Initialization.** Loading Llama 3.1 in 4-bit precision via `bitsandbytes` and injecting LoRA adapters to attention and MLP matrices.
*   **Phase 3: Two-Stage Training.**
    *   *3.1 SFT:* Teaching the model raw SQL syntax and strict Markdown-only outputs.
    *   *3.2 DPO:* Penalizing hallucinations (flipped operators, invented columns) using KL-divergence logic.
*   **Phase 4: Tensor Merging & Evaluation.** Fusing adapters into FP16 base weights and running anti-hallucination stress tests.
*   **Phase 5: Production Deployment.** Booting a headless, OpenAI-compatible API server via `vLLM` with PagedAttention, and tunneling it to the public web via PyNgrok.

# **Phase 1: Data Engineering & Preparation**
Ingesting the `b-mc2/sql-create-context` dataset, converting rows to strict Hugging Face ChatML format, and utilizing a custom Regex Heuristic Corruption Engine to build negative pairs for DPO alignment.

In [ ]:
!pip install datasets pandas

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)

In [ ]:
from datasets import load_dataset

# 1. Download the dataset from Hugging Face
print("Downloading dataset...")
dataset = load_dataset("b-mc2/sql-create-context")

Downloading dataset...

README.md:   0%|          | 0.00/4.43k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sql_create_context_v4.json: reconstructing file:   0%|          |  0.00B / 21.8MB

sql_create_context_v4.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78577 [00:00<?, ? examples/s]

In [ ]:
print(type(dataset))
print(dataset.keys())

<class 'datasets.dataset_dict.DatasetDict'>
dict_keys(['train'])

In [ ]:
# 2. Extract the 'train' split
train_data = dataset["train"]

In [ ]:
# 3. Print basic information
print(f"\nTotal rows in dataset: {len(train_data)}")

Total rows in dataset: 78577

In [ ]:
print(type(train_data))

<class 'datasets.arrow_dataset.Dataset'>

In [ ]:
print(train_data[:5])

{'answer': ['SELECT COUNT(*) FROM head WHERE age > 56', 'SELECT name, born_state, age FROM head ORDER BY age', 'SELECT creation, name, budget_in_billions FROM department', 'SELECT MAX(budget_in_billions), MIN(budget_in_billions) FROM department', 'SELECT AVG(num_employees) FROM department WHERE ranking BETWEEN 10 AND 15'], 'question': ['How many heads of the departments are older than 56 ?', 'List the name, born state and age of the heads of departments ordered by age.', 'List the creation year, name and budget of each department.', 'What are the maximum and minimum budget of the departments?', 'What is the average number of employees of the departments whose rank is between 10 and 15?'], 'context': ['CREATE TABLE head (age INTEGER)', 'CREATE TABLE head (name VARCHAR, born_state VARCHAR, age VARCHAR)', 'CREATE TABLE department (creation VARCHAR, name VARCHAR, budget_in_billions VARCHAR)', 'CREATE TABLE department (budget_in_billions INTEGER)', 'CREATE TABLE department (num_employees INTEGER, ranking INTEGER)']}

In [ ]:
print(train_data.column_names)

['answer', 'question', 'context']

In [ ]:
# 4. Inspect the very first row
print("\n--- Raw Data Example (Row 0) ---")
print(train_data[0])

--- Raw Data Example (Row 0) ---
{'answer': 'SELECT COUNT(*) FROM head WHERE age > 56', 'question': 'How many heads of the departments are older than 56 ?', 'context': 'CREATE TABLE head (age INTEGER)'}

In [ ]:
def format_sft_messages(row):
    """
    Converts raw dataset rows into the universal Hugging Face 'messages' format.
    Enforces strict Markdown formatting for robust downstream parsing.
    """
    system_message = {
        "role": "system",
        "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."
    }

    user_message = {
        "role": "user",
        "content": f"Database Schema:\n{row['context']}\n\nQuestion:\n{row['question']}"
    }

    assistant_message = {
        "role": "assistant",
        "content": f"```sql\n{row['answer']}\n```"
    }

    return {"messages": [system_message, user_message, assistant_message]}

In [ ]:
print("Splitting dataset into Train and Test splits...")
split_dataset = train_data.train_test_split(test_size=0.05, seed=42)

Splitting dataset into Train and Test splits...

In [ ]:
# 2. Apply the transformation to BOTH splits
print("Formatting datasets into 'messages' format...")
sft_dataset = split_dataset.map(format_sft_messages, remove_columns = train_data.column_names)

Formatting datasets into 'messages' format...

Map:   0%|          | 0/74648 [00:00<?, ? examples/s]

Map:   0%|          | 0/3929 [00:00<?, ? examples/s]

In [ ]:
# 3. Verify the architecture
print("\n--- Pipeline Verification ---")
print(f"Training Rows (For Phase 3): {len(sft_dataset['train'])}")
print(f"Testing Rows (For Phase 4): {len(sft_dataset['test'])}")

print("\n--- Production-Grade SFT Messages (Train Row 0) ---")
import json
print(json.dumps(sft_dataset['train'][0], indent=2))

--- Pipeline Verification ---
Training Rows (For Phase 3): 74648
Testing Rows (For Phase 4): 3929

--- Production-Grade SFT Messages (Train Row 0) ---
{
  "messages": [
    {
      "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block.",
      "role": "system"
    },
    {
      "content": "Database Schema:\nCREATE TABLE table_256286_39 (description VARCHAR, _percentage_yes VARCHAR)\n\nQuestion:\nWhat is the measure where the yes% is 44.06%?",
      "role": "user"
    },
    {
      "content": "```sql\nSELECT description FROM table_256286_39 WHERE _percentage_yes = \"44.06%\"\n```",
      "role": "assistant"
    }
  ]
}

In [ ]:
import re

def generate_dpo_pairs(row):
    correct_sql = row['answer']
    bad_sql = correct_sql

    # --- EXPANDED & REGEX-BULLETPROOF CORRUPTION ENGINE ---

    # 1. Ordering Mistakes (Handling variable whitespace and case)
    if re.search(r"\s+DESC\b", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+DESC\b", " ASC", bad_sql, flags =re.IGNORECASE )
    elif re.search(r"\s+ASC\b", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+ASC\b", " DESC", bad_sql, flags=re.IGNORECASE)

    # 2. Aggregation Mistakes
    elif re.search(r"\bMAX\(", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\bMAX\(", "MIN(", bad_sql, flags=re.IGNORECASE)
    elif re.search(r"\bMIN\(", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\bMIN\(", "MAX(", bad_sql, flags=re.IGNORECASE)
    elif re.search(r"\bCOUNT\(", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\bCOUNT\(", "SUM(", bad_sql, flags=re.IGNORECASE)
    elif re.search(r"\bAVG\(", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\bAVG\(", "COUNT(", bad_sql, flags=re.IGNORECASE)

    # 3. Operator Mistakes (Handling variable spaces around the operators)
    elif re.search(r"\s+>\s+", bad_sql):
        bad_sql = re.sub(r"\s+>\s+", " < ", bad_sql)
    elif re.search(r"\s+<\s+", bad_sql):
        bad_sql = re.sub(r"\s+<\s+", " > ", bad_sql)
    elif re.search(r"\s+=\s+", bad_sql):
        bad_sql = re.sub(r"\s+=\s+", " != ", bad_sql)
    elif re.search(r"\s+AND\s+", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+AND\s+", " OR ", bad_sql, flags=re.IGNORECASE)
    elif re.search(r"\s+OR\s+", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+OR\s+", " AND ", bad_sql, flags=re.IGNORECASE)

    # 4. Pattern Matching
    elif re.search(r"\s+LIKE\s+", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+LIKE\s+", " NOT LIKE ", bad_sql, flags=re.IGNORECASE)

    # 5. Fallbacks
    elif re.search(r"\s+GROUP BY\b", bad_sql, re.IGNORECASE):
        bad_sql = re.sub(r"\s+GROUP BY\b.*", "", bad_sql, flags=re.IGNORECASE)
    else:
        bad_sql = re.sub(r"\bFROM\b", ", hallucinated_col FROM", bad_sql, flags=re.IGNORECASE)

    # --- DPO FORMATTING ---
    system_message = {
        "role": "system",
        "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."
    }

    user_message = {
        "role": "user",
        "content": f"Database Schema:\n{row['context']}\n\nQuestion:\n{row['question']}"
    }

    return {
        "prompt": [system_message, user_message],
        "chosen": [{"role": "assistant", "content": f"```sql\n{correct_sql}\n```"} ],
        "rejected": [ {"role": "assistant", "content": f"```sql\n{bad_sql}\n```"} ]
    }

In [ ]:
# (The rest of the pipeline mapping and filtering code remains exactly the same!)
print("Generating DPO dataset via expanded heuristic corruption...")
raw_dpo_dataset = split_dataset['train'].map(generate_dpo_pairs, remove_columns=train_data.column_names)

Generating DPO dataset via expanded heuristic corruption...

Map:   0%|          | 0/74648 [00:00<?, ? examples/s]

In [ ]:
def filter_identical_pairs(row):
    return row['chosen'][0]['content'] != row['rejected'][0]['content']

print("Filtering identical chosen/rejected pairs...")
dpo_dataset = raw_dpo_dataset.filter(filter_identical_pairs)

Filtering identical chosen/rejected pairs...

Filter:   0%|          | 0/74648 [00:00<?, ? examples/s]

In [ ]:
print(f"\n--- DPO Dataset Pipeline Summary ---")
print(f"Total Raw Pairs: {len(raw_dpo_dataset)}")
print(f"Valid Filtered DPO Pairs: {len(dpo_dataset)}")
print(f"Dropped Pairs: {len(raw_dpo_dataset) - len(dpo_dataset)}")

--- DPO Dataset Pipeline Summary ---
Total Raw Pairs: 74648
Valid Filtered DPO Pairs: 74648
Dropped Pairs: 0

In [ ]:
# 1. Install Hugging Face Hub and Transformers
!pip install transformers huggingface_hub

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [ ]:
from huggingface_hub import notebook_login
from transformers import AutoTokenizer

In [ ]:
# 2. Authenticate with Hugging Face
print("Please authenticate with your Hugging Face Access Token:")
notebook_login()

Please authenticate with your Hugging Face Access Token:

In [ ]:
# 3. Load the Official Llama 3.1 Tokenizer
model_id = "meta-llama/Llama-3.1-8B-Instruct"
print(f"\nDownloading Tokenizer for {model_id}...")

Downloading Tokenizer for meta-llama/Llama-3.1-8B-Instruct...

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_id)

# 4. Validate the Chat Template on Row 0 of our SFT dataset
print("\n--- Validating Llama 3.1 Chat Template (Row 0) ---")
formatted_prompt = tokenizer.apply_chat_template(
    sft_dataset['train'][0]["messages"],
    tokenize=False
)
print(formatted_prompt)

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

--- Validating Llama 3.1 Chat Template (Row 0) ---
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block.<|eot_id|><|start_header_id|>user<|end_header_id|>

Database Schema:
CREATE TABLE table_256286_39 (description VARCHAR, _percentage_yes VARCHAR)

Question:
What is the measure where the yes% is 44.06%?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

```sql
SELECT description FROM table_256286_39 WHERE _percentage_yes = "44.06%"
```<|eot_id|>

In [ ]:
# --- THE SENIOR ENGINEER PATCHES ---
# Patch 1: Llama 3 doesn't have a pad token. We map it to the EOS token.
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    print("Crucial Patch Applied: pad_token set to eos_token")


# 3. Validate the Chat Template on Row 0
print("\n--- Validating Llama 3.1 Chat Template (Row 0) ---")
formatted_prompt = tokenizer.apply_chat_template(
    sft_dataset['train'][0]["messages"],
    tokenize = False
)
print(formatted_prompt)



# 4. Measure Sequence Length (Token Count) to prevent OOM in Phase 2
tokens = tokenizer.apply_chat_template(
    sft_dataset['train'][0]["messages"],
    tokenize = True
)
print(f"\nTotal Tokens in this specific prompt: {len(tokens)}")

Crucial Patch Applied: pad_token set to eos_token

--- Validating Llama 3.1 Chat Template (Row 0) ---
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block.<|eot_id|><|start_header_id|>user<|end_header_id|>

Database Schema:
CREATE TABLE table_256286_39 (description VARCHAR, _percentage_yes VARCHAR)

Question:
What is the measure where the yes% is 44.06%?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

```sql
SELECT description FROM table_256286_39 WHERE _percentage_yes = "44.06%"
```<|eot_id|>

Total Tokens in this specific prompt: 2

In [ ]:
from google.colab import drive
print("Mounting Google Drive...")
drive.mount('/content/drive')

from transformers import AutoTokenizer
from datasets import load_from_disk

# 1. Load Tokenizer & Dataset
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")
sft_data = load_from_disk('/content/drive/MyDrive/Enterprise_SQL_LLM/sft_dataset')

# 2. Check the real token length!
tokens = tokenizer.apply_chat_template(sft_data['train'][0]["messages"], tokenize=True)

Mounting Google Drive...
Mounted at /content/drive
Real Token Count: 2

In [ ]:
print(f"Real Token Count: {len(tokens['input_ids'])}")

Real Token Count: 144

In [ ]:
print(tokens)

{'input_ids': [128000, 128006, 9125, 128007, 271, 38766, 1303, 33025, 2696, 25, 6790, 220, 2366, 18, 198, 15724, 2696, 25, 220, 1627, 10263, 220, 2366, 19, 271, 2675, 527, 459, 6335, 8029, 18328, 13, 4718, 1193, 2683, 374, 311, 3350, 4839, 11, 2764, 8029, 20126, 3196, 26549, 389, 279, 3984, 4729, 11036, 13, 3234, 539, 10552, 279, 3319, 477, 2997, 7669, 1697, 55810, 13, 3494, 1193, 279, 8029, 3319, 4871, 264, 51594, 2082, 2565, 13, 128009, 128006, 882, 128007, 271, 6116, 12824, 512, 23421, 14700, 2007, 62, 4146, 17361, 62, 2137, 320, 4789, 38689, 11, 721, 41650, 60844, 38689, 696, 14924, 512, 3923, 374, 279, 6767, 1405, 279, 10035, 4, 374, 220, 2096, 13, 2705, 4, 30, 128009, 128006, 78191, 128007, 271, 74694, 3628, 198, 4963, 4096, 4393, 2007, 62, 4146, 17361, 62, 2137, 5401, 721, 41650, 60844, 284, 330, 2096, 13, 2705, 64961, 74694, 128009], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
from google.colab import drive
import os

In [ ]:
# 1. Mount Google Drive to the notebook
print("Mounting Google Drive...")
drive.mount( '/content/drive' )

Mounting Google Drive...
Mounted at /content/drive

In [ ]:
# 2. Create a dedicated project folder in your Drive
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
os.makedirs(project_path, exist_ok=True)
print(f"\nProject folder secured at: {project_path}")

# 3. Save the datasets permanently
print("\nSaving SFT Dataset to Drive...")
sft_dataset.save_to_disk(f"{project_path}/sft_dataset")

print("Saving DPO Dataset to Drive...")
dpo_dataset.save_to_disk(f"{project_path}/dpo_dataset")

print("\n PHASE 1 COMPLETE! Data is safely locked in the vault.")

Project folder secured at: /content/drive/MyDrive/Enterprise_SQL_LLM

Saving SFT Dataset to Drive...

Saving the dataset (0/1 shards):   0%|          | 0/74648 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/3929 [00:00<?, ? examples/s]

Saving DPO Dataset to Drive...

Saving the dataset (0/1 shards):   0%|          | 0/74648 [00:00<?, ? examples/s]

 PHASE 1 COMPLETE! Data is safely locked in the vault.

# **Phase 2: Base Model Initialization & LoRA Injection**
Loading Meta's Llama 3.1 8B Instruct model directly into VRAM using 4-bit `bitsandbytes` quantization, and injecting Rank 16 LoRA adapters targeting all attention modules to prepare for parameter-efficient training.

In [ ]:
# 1. Verify the Hardware (This asks the Linux server what GPU is plugged into the motherboard)
print("--- Hardware Verification ---")
!nvidia-smi

--- Hardware Verification ---
Sat Aug  8 18:26:08 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
from google.colab import drive
from huggingface_hub import notebook_login
import os

# 1. Mount Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive')

# 2. Set project path variable
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'

# 3. Authenticate with Hugging Face (Required to download Llama 3.1)
print("\nPlease authenticate with Hugging Face:")
notebook_login()

Mounting Google Drive...
Mounted at /content/drive

Please authenticate with Hugging Face:

In [ ]:
# 2. Install Unsloth and its heavily optimized dependencies
# We install directly from Unsloth's GitHub to ensure Colab compatibility
print("\n--- Installing Unsloth & Dependencies ---")
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

--- Installing Unsloth & Dependencies ---
Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-ngllrac7/unsloth_5116c2d9e4494adea7e540c4f0c8d747
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-ngllrac7/unsloth_5116c2d9e4494adea7e540c4f0c8d747
  Resolved https://github.com/unslothai/unsloth.git to commit b2158c2cd90e8b64f4d49484495d4e9a906dfb96
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.26.8)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting structlog>=24.1.0 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading structlog-26.1.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (8.4.2)
Collecting unsloth_zoo>=2026.8.10 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.8.10-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (26.2)
Collecting tyro (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.15-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.23.0)
Collecting hf_transfer (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.50.0-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.6.0)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-25.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.16.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.20.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.19.1)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.8.10->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.16.3)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.5.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.9.7)

In [ ]:
# 3. Install the exact Hugging Face libraries needed for QLoRA and DPO
# --no-deps prevents pip from accidentally overriding Unsloth's custom PyTorch versions
!pip install --no-deps xformers trl peft accelerate bitsandbytes

Collecting xformers
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.24.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.50.0)
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 87.1 MB/s eta 0:00:00
Installing collected packages: xformers
Successfully installed xformers-0.0.35

In [ ]:
from unsloth import FastLanguageModel
import torch
# 1. Define Hardware Limits & Quantization Settings
max_seq_length = 2048 # Strict VRAM protection (prevents the 128k OOM crash)
dtype = None          # Auto-detects optimal hardware precision
load_in_4bit = True  # Activates bitsandbytes NF4 compression

model_id = "meta-llama/Llama-3.1-8B-Instruct"
print(f"--- Downloading and Quantizing {model_id} ---")

# 2. Load Model & Tokenizer directly into VRAM
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_id,
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    token = True, # This automatically uses your active huggingface_hub login
)

print("\n[OK] BASE MODEL SUCCESSFULLY LOADED IN 4-BIT!")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
--- Downloading and Quantizing meta-llama/Llama-3.1-8B-Instruct ---
==((====))==  Unsloth 2026.8.15: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3.1-8b-instruct-unsloth-bnb-4bit as a legacy tokenizer.

[OK] BASE MODEL SUCCESSFULLY LOADED IN 4-BIT!

In [ ]:
# --- Sub-Phase 2.3: Injecting the LoRA Adapters ---
print("--- Injecting LoRA Adapters ---")

model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # The Rank. 16 is the industry standard sweet spot for coding/SQL tasks.
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"], # Targeting every linear layer in Llama 3.1
    lora_alpha = 16, # The scaling factor for the weight updates.
    lora_dropout = 0, # Unsloth specifically optimizes a dropout of 0 for massive speedups.
    bias = "none",    # Optimized to prevent unnecessary parameter training.

    # --- THE MAGIC SETTING ---
    # Gradient checkpointing saves massive VRAM by offloading activations during the forward pass.
    # Setting this to "unsloth" activates their custom OpenAI Triton kernels.
    use_gradient_checkpointing = "unsloth",

    random_state = 3407, # Standard seed for reproducibility.
    use_rslora = False,
    loftq_config = None,
)

print("\n[OK] LORA ADAPTERS SUCCESSFULLY INJECTED!")

# Validation: Let's count the exact number of parameters we are actually training
trainable_params, all_param = model.get_nb_trainable_parameters()
percentage = 100 * trainable_params / all_param

print(f"\n--- Parameter Math ---")
print(f"Total Base Parameters: {all_param:,}")
print(f"Trainable LoRA Parameters: {trainable_params:,}")
print(f"Percentage Being Trained: {percentage:.4f}%")

--- Injecting LoRA Adapters ---

Unsloth 2026.8.15 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

[OK] LORA ADAPTERS SUCCESSFULLY INJECTED!

--- Parameter Math ---
Total Base Parameters: 8,072,204,288
Trainable LoRA Parameters: 41,943,040
Percentage Being Trained: 0.5196%

# **Phase 3: Two-Stage Alignment (SFT & DPO)**
**Step 1:** Supervised Fine-Tuning (SFT) to teach strict SQL syntax and Markdown encapsulation.

**Step 2:** Violently flushing VRAM and shifting to Direct Preference Optimization (DPO) to penalize hallucination patterns via KL-divergence.

In [ ]:
# --- SUB-PHASE 3.1: SUPERVISED FINE-TUNING (SFT) ---
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported
from datasets import load_from_disk

# 1. Reload our prepared dataset from the Google Drive vault
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
print(f"Loading SFT dataset from {project_path}...")
sft_dataset = load_from_disk(f"{project_path}/sft_dataset")

# Unsloth requires an explicit function to convert the 'messages' dictionary into a raw string
def formatting_prompts_func(examples):
    texts = []
    for messages in examples["messages"]:

        # --- THE ARROW PATCH ---
        # If Apache Arrow flipped our list of dicts into a dict of lists, zip it back!
        if isinstance(messages, dict):
            messages = [
                { "role": r , "content": c }
                for r, c in zip(messages["role"], messages["content"])
            ]

        # This applies the Llama 3.1 Chat Template to our dataset on the fly!
        text = tokenizer.apply_chat_template(messages, tokenize=False)
        texts.append(text)
    return texts

# 2. Configure the SFT Trainer
# TRL's SFTTrainer natively detects the 'messages' column and applies the tokenizer's chat template!
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = sft_dataset["train"],
    eval_dataset = sft_dataset["test"],
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Set to False to ensure strict ChatML formatting isn't mangled
    formatting_func = formatting_prompts_func,
    args = TrainingArguments(
        per_device_train_batch_size = 2,  # The max size for 15GB VRAM
        gradient_accumulation_steps = 4,  # Simulates a larger batch size of 8
        warmup_steps = 5,
        max_steps = 100, # We are running a fast 100-step cycle to ensure Colab doesn't timeout!
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(), # Auto-detects T4 (fp16) vs A100 (bf16)
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit", # 8-bit AdamW optimizer saves massive memory!
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Disable wandb for now to keep things moving fast
    ),
)

# 3. Execute the Training Loop
print("\nINITIATING SUPERVISED FINE-TUNING (SFT)")
trainer_stats = trainer.train()

# 4. Save the LoRA Adapter Weights to Google Drive (CRITICAL SAFEGUARD)
print("\n--- SAVING ADAPTERS TO GOOGLE DRIVE ---")
model.save_pretrained(f"{project_path}/lora_sft_model")
tokenizer.save_pretrained(f"{project_path}/lora_sft_model")
print("\nSFT COMPLETE! The model now speaks perfect SQL.")

Loading SFT dataset from /content/drive/MyDrive/Enterprise_SQL_LLM...
Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/74648 [00:00<?, ? examples/s]

Unsloth: We found double BOS tokens - we shall remove one automatically.

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/3929 [00:00<?, ? examples/s]

INITIATING SUPERVISED FINE-TUNING (SFT)

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 74,648 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-100/tokenizer_config.json.

--- SAVING ADAPTERS TO GOOGLE DRIVE ---

Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/Enterprise_SQL_LLM/lora_sft_model/tokenizer_config.json.

SFT COMPLETE! The model now speaks perfect SQL.

In [ ]:
# --- THE BULLETPROOF FORMATTING TEST ---
# 1. Reload our prepared dataset from the Google Drive vault
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
print(f"Loading SFT dataset from {project_path}...")
sft_dataset = load_from_disk(f"{project_path}/sft_dataset")

print("[INFO] Simulating SFTTrainer batch processing...\n")

# 1. Slice a tiny "batch" of 2 examples directly from the dataset
test_batch = sft_dataset["train"][:2]

try:
    # 2. Run our patched formatting function
    test_output = formatting_prompts_func(test_batch)
    print("[SUCCESS] The formatting function processed the batch perfectly!\n")

    # 3. Print a preview of the stitched string to verify the markers
    print("--- FORMATTED PROMPT PREVIEW (Row 0) ---")
    print(test_output[0])

except Exception as e:
    print(f"\n[FAILED] The function crashed with error: {e}")

Loading SFT dataset from /content/drive/MyDrive/Enterprise_SQL_LLM...
[INFO] Simulating SFTTrainer batch processing...

[SUCCESS] The formatting function processed the batch perfectly!

--- FORMATTED PROMPT PREVIEW (Row 0) ---
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block.<|eot_id|><|start_header_id|>user<|end_header_id|>

Database Schema:
CREATE TABLE table_256286_39 (description VARCHAR, _percentage_yes VARCHAR)

Question:
What is the measure where the yes% is 44.06%?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

```sql
SELECT description FROM table_256286_39 WHERE _percentage_yes = "44.06%"
```<|eot_id|>

In [ ]:
# --- SUB-PHASE 3.2: ADAPTER MANAGEMENT & VRAM FLUSHING ---
import gc
import torch
from datasets import load_from_disk
from unsloth import PatchDPOTrainer

print("--- INITIAL VRAM STATE ---")
print(f"Allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
print(f"Reserved:  {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

# 1. Annihilate the SFT Trainer and Optimizer States
print("\nDestroying SFT Trainer to free memory...")
del trainer

# 2. Force Python Garbage Collection
gc.collect()

# 3. Flush the PyTorch GPU Cache
torch.cuda.empty_cache()

print("\n--- POST-FLUSH VRAM STATE ---")
print(f"Allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
print(f"Reserved:  {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

# 4. Load the DPO Dataset from the Google Drive Vault
# Ensure project_path is defined if you are running this in a new cell
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
print(f"\nLoading DPO dataset from {project_path}...")
dpo_dataset = load_from_disk(f"{project_path}/dpo_dataset")
# Re-split the flat dataset into Train and Test splits on the fly!
dpo_dataset = dpo_dataset.train_test_split(test_size=0.05, seed=42)



# 5. Apply Unsloth's DPO Memory Patch
# This is a critical Unsloth function that patches the DPOTrainer to use Triton kernels
# and simulates the "Reference Model" without actually doubling your VRAM!
PatchDPOTrainer()

print("\n VRAM FLUSHED. DPO DATASET LOADED. READY FOR PHASE 3.3.")

--- INITIAL VRAM STATE ---
Allocated: 5.99 GB
Reserved:  6.09 GB

Destroying SFT Trainer to free memory...

--- POST-FLUSH VRAM STATE ---
Allocated: 5.91 GB
Reserved:  5.94 GB

Loading DPO dataset from /content/drive/MyDrive/Enterprise_SQL_LLM...

 VRAM FLUSHED. DPO DATASET LOADED. READY FOR PHASE 3.3.

In [ ]:
# --- SUB-PHASE 3.3: DIRECT PREFERENCE OPTIMIZATION (DPO) ---
from trl import DPOTrainer, DPOConfig
from unsloth import is_bfloat16_supported

print("[INFO] INITIATING DIRECT PREFERENCE OPTIMIZATION (DPO)...")

# 1. Configure the DPO Trainer using DPOConfig (Required by modern TRL / Unsloth)
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # Unsloth's PatchDPOTrainer handles reference model internally!
    tokenizer = tokenizer,
    train_dataset = dpo_dataset["train"],
    eval_dataset = dpo_dataset["test"],

    args = DPOConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # Fast 60-step DPO alignment pass
        learning_rate = 5e-5, # Lower learning rate for sensitive DPO pass
        beta = 0.1, # Penalty factor preventing policy drift
        max_length = max_seq_length,
        max_prompt_length = 1024,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "dpo_outputs",
        report_to = "none",
    ),
)

# 2. Execute the DPO Training Loop
dpo_stats = dpo_trainer.train()

# 3. Save the Final, Hallucination-Free Adapters to Google Drive
print("\n[INFO] SAVING FINAL DPO ADAPTERS TO GOOGLE DRIVE...")
model.save_pretrained(f"{project_path}/lora_dpo_final_model")
tokenizer.save_pretrained(f"{project_path}/lora_dpo_final_model")

print("\n[SUCCESS] PHASE 3 COMPLETE! You have successfully aligned an Enterprise SQL Model!")

[INFO] INITIATING DIRECT PREFERENCE OPTIMIZATION (DPO)...

Extracting prompt in train dataset (num_proc=2):   0%|          | 0/70915 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=2):   0%|          | 0/70915 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=2):   0%|          | 0/70915 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=2):   0%|          | 0/3733 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=2):   0%|          | 0/3733 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=2):   0%|          | 0/3733 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 70,915 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in dpo_outputs/checkpoint-60/tokenizer_config.json.

[INFO] SAVING FINAL DPO ADAPTERS TO GOOGLE DRIVE...

Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/Enterprise_SQL_LLM/lora_dpo_final_model/tokenizer_config.json.

[SUCCESS] PHASE 3 COMPLETE! You have successfully aligned an Enterprise SQL Model!

# **Phase 4: Evaluation & Tensor Merging**
Restoring the environment, running deterministic anti-hallucination stress tests on held-out data, and fusing the trained LoRA adapters into the FP16 base weights to generate a standalone 15GB `.safetensors` model for vLLM.

In [ ]:
# ==========================================
# PHASE 4.1: ENVIRONMENT RESTORE & DETERMINISTIC INFERENCE
# ==========================================

# 1. Mount Drive & Reinstall Dependencies (Crucial after Colab disconnect)
from google.colab import drive
drive.mount('/content/drive')

print("\n[INFO] Re-installing Unsloth and dependencies...")
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes

Mounted at /content/drive

[INFO] Re-installing Unsloth and dependencies...
Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-y3_e0i9d/unsloth_e1c3db579788417ca50c7668e5f3f966
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-y3_e0i9d/unsloth_e1c3db579788417ca50c7668e5f3f966
  Resolved https://github.com/unslothai/unsloth.git to commit 4f0d691cfc6530b955198d2f18d8265cb161e47d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.26.8)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting structlog>=24.1.0 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading structlog-26.1.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (8.4.2)
Collecting unsloth_zoo>=2026.8.12 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.8.12-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (26.2)
Collecting tyro (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.15-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.23.0)
Collecting hf_transfer (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.50.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.6.0)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-25.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.16.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.20.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.19.1)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.16.3)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.5.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.9.7)

In [ ]:
# 2. Load the Saved DPO Model from the Vault
from unsloth import FastLanguageModel
import torch

project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
print(f"\n[INFO] Loading fine-tuned model from {project_path}/lora_dpo_final_model...")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = f"{project_path}/lora_dpo_final_model", # Pointing directly to your saved weights!
    max_seq_length = 2048,
    load_in_4bit = True,
)

# 3. Activate Unsloth's 2x Inference Speedup Mode
print("\n[INFO] Setting up model for ultra-fast deterministic inference...")
FastLanguageModel.for_inference( model )

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

[INFO] Loading fine-tuned model from /content/drive/MyDrive/Enterprise_SQL_LLM/lora_dpo_final_model...
==((====))==  Unsloth 2026.8.18: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load /content/drive/MyDrive/Enterprise_SQL_LLM/lora_dpo_final_model as a legacy tokenizer.
Unsloth 2026.8.18 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

[INFO] Setting up model for ultra-fast deterministic inference...

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(128256, 4096, padding_idx=128004)
        (layers): ModuleList(
          (0): LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=14336, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=14336, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
          (1): LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=14336, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=14336, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
          (2-31): 30 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=14336, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=14336, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=14336, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
    )
  )
)

In [ ]:
# 4. We Define a tricky, unseen enterprise test case
test_schema = """
CREATE TABLE enterprise_employees (
    emp_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10, 2),
    hire_date DATE
);
"""

test_question = "Find the top 3 highest-paid employees in the Engineering department who were hired after the year 2022."

# 5. Format using our strict ChatML System Prompt
messages = [
    {
        "role": "system",
        "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."
    },
    {
        "role": "user",
        "content": f"Database Schema:\n{test_schema}\n\nQuestion:\n{test_question}"
    }
]

# 6. Tokenize with the crucial 'add_generation_prompt=True'
prompt = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True,
    return_dict = True,
    return_tensors = "pt"
).to("cuda")

# 7. Generate SQL with Temperature = 0 (Strict Determinism)
print("\n--- GENERATING SQL QUERY ---")
outputs = model.generate(
    **prompt,
    max_new_tokens = 256,
    max_length = None,
    use_cache = True,
    do_sample = False,
)

# 8. Decode and display the pure SQL response
generated_response = tokenizer.decode(outputs[0][prompt["input_ids"].shape[1]:], skip_special_tokens=True)
print("\n[MODEL RESPONSE]:")
print(generated_response)

--- GENERATING SQL QUERY ---

[MODEL RESPONSE]:
```sql
SELECT MAX(salary) AS max_salary, first_name, last_name
FROM enterprise_employees
WHERE department = "Engineering" AND hire_date > 2022
GROUP BY first_name, last_name
ORDER BY max_salary DESC
LIMIT 3
```

In [ ]:
# ==========================================
# PHASE 4.2: ANTI-HALLUCINATION STRESS TESTS
# ==========================================
print("[INFO] Initiating Phase 4.2 Stress Tests...\n")

def test_sql_generation(test_name, schema, question):
    print(f"==========================================")
    print(f" TEST: {test_name}")
    print(f"==========================================")
    print(f"Question: {question}\n")

    messages = [
        {"role": "system", "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."},
        {"role": "user", "content": f"Database Schema:\n{schema}\n\nQuestion:\n{question}"}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt"
    ).to("cuda")

    outputs = model.generate (
        **prompt,
        max_new_tokens = 256,
        max_length=None,
        use_cache = True,
        do_sample=False,
    )

    response = tokenizer.decode(outputs[0][ prompt["input_ids"].shape[1]: ], skip_special_tokens=True)
    print("[GENERATED SQL]:")
    print(response)
    print("\n")


# --- TEST 1: COLUMN HALLUCINATION ---
# Standard models often hallucinate a 'department_id' or 'revenue' column.
schema_1 = """
CREATE TABLE stores (
    store_code VARCHAR(10) PRIMARY KEY,
    city VARCHAR(50),
    total_sales DECIMAL(15, 2)
);
"""
question_1 = "Show me the cities that have more than 50000 in total sales, ordered by highest sales first."
test_sql_generation("Column Hallucination & Ordering", schema_1, question_1)


# --- TEST 2: AGGREGATION & OPERATOR FLIPPING ---
# We heavily penalized flipping MAX/MIN and ASC/DESC in DPO. Let's see if it learned.
schema_2 = """
CREATE TABLE server_logs (
    log_id INT,
    cpu_utilization FLOAT,
    memory_usage FLOAT,
    timestamp DATETIME
);
"""
question_2 = "Find the timestamp of the absolute lowest cpu utilization recorded."
test_sql_generation("Aggregation & Operator Fidelity", schema_2, question_2)


# --- TEST 3: MULTI-TABLE JOIN ADHERENCE ---
# Standard models fail to use correct Foreign Keys.
schema_3 = """
CREATE TABLE patients (
    patient_id INT PRIMARY KEY,
    full_name VARCHAR(100),
    age INT
);
CREATE TABLE appointments (
    appt_id INT PRIMARY KEY,
    patient_id INT,
    doctor_name VARCHAR(100),
    visit_date DATE
);
"""
question_3 = "List the full names of patients who have an appointment with Dr. Smith after 2024-01-01."
test_sql_generation("Multi-Table JOIN Logic", schema_3, question_3)

[INFO] Initiating Phase 4.2 Stress Tests...

==========================================
 TEST: Column Hallucination & Ordering
==========================================
Question: Show me the cities that have more than 50000 in total sales, ordered by highest sales first.

[GENERATED SQL]:
```sql
SELECT MAX(CAST(REPLACE(TOTAL_SALES, ",", "") AS INTEGER)) / 100000 AS max_sales, CITY
FROM stores
WHERE TOTAL_SALES > 50000
GROUP BY CITY
ORDER BY MAX(CAST(REPLACE(TOTAL_SALES, ",", "") AS INTEGER)) / 100000 DESC
```


==========================================
 TEST: Aggregation & Operator Fidelity
==========================================
Question: Find the timestamp of the absolute lowest cpu utilization recorded.

[GENERATED SQL]:
```sql
SELECT MIN(timestamp) AS timestamp
FROM server_logs
WHERE cpu_utilization = (SELECT MIN(cpu_utilization) FROM server_logs)
```


==========================================
 TEST: Multi-Table JOIN Logic
==========================================
Question: List the full names of patients who have an appointment with Dr. Smith after 2024-01-01.

[GENERATED SQL]:
```sql
SELECT T1.full_name FROM patients AS T1 JOIN appointments AS T2 ON T1.patient_id = T2.patient_id WHERE T2.doctor_name = "Dr. Smith" AND T2.visit_date > "2024-01-01"
```

In [ ]:
# ==========================================
# PHASE 4.3: BATCH EVALUATION ON HELD-OUT TEST SET (PATCHED)
# ==========================================
from datasets import load_from_disk
import torch

print("\n[INFO] Loading held-out test dataset...")
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
sft_dataset = load_from_disk(f"{project_path}/sft_dataset")

# Select the first 3 samples from the unseen test split
test_batch = sft_dataset['test'].select(range(3))

print("==========================================")
print(" BATCH INFERENCE ON HELD-OUT DATASET")
print("==========================================\n")


for i, row in enumerate(test_batch):
    messages = row["messages"]

    # --- THE ARROW PATCH (Defensive Engineering) ---
    # If Apache Arrow flipped our list of dicts into a dict of lists, zip it back!
    if isinstance( messages, dict ):
        messages = [
            { "role": r , "content": c }
            for r, c in zip(messages['role'], messages['content'])
        ]

    # Now it is perfectly safe to slice!
    test_messages = messages[:-1]
    ground_truth_sql = messages[-1]["content"]

    prompt = tokenizer.apply_chat_template(
        test_messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt"
    ).to("cuda")

    outputs = model.generate(
        **prompt,
        max_new_tokens = 256,
        max_length = None,
        use_cache = True,
        do_sample=False
    )

    predicted_sql = tokenizer.decode(outputs[0][prompt["input_ids"].shape[1]:], skip_special_tokens=True)

    print(f"--- SAMPLE {i+1} ---")
    print(f"[EXPECTED (Ground Truth)]:\n{ground_truth_sql}\n")
    print(f"[PREDICTED (Model Output)]:\n{predicted_sql}\n")
    print("-" * 50 + "\n")

[INFO] Loading held-out test dataset...
==========================================
 BATCH INFERENCE ON HELD-OUT DATASET
==========================================

--- SAMPLE 1 ---
[EXPECTED (Ground Truth)]:
```sql
SELECT venue FROM table_name_50 WHERE away_team = "essendon"
```

[PREDICTED (Model Output)]:
```sql
SELECT MAX(CAST(REPLACE(SUBSTR(venue, 1, INSTR(venue, "vs") - 1), "essendon", "") AS INTEGER)) + 1 AS max_away_team_ranking
FROM table_name_50
WHERE away_team = "essendon"
```

--------------------------------------------------

--- SAMPLE 2 ---
[EXPECTED (Ground Truth)]:
```sql
SELECT MIN(game) FROM table_name_61 WHERE opponent = "phoenix" AND record = "29-17"
```

[PREDICTED (Model Output)]:
```sql
SELECT MIN(game) VARCHAR + " vs " + opponent AS lowest_game_against_phoenix
FROM table_name_61
WHERE opponent = "phoenix" AND record = 29 - 17
```

--------------------------------------------------

--- SAMPLE 3 ---
[EXPECTED (Ground Truth)]:
```sql
SELECT opponent FROM table_name_37 WHERE week = "4"
```

[PREDICTED (Model Output)]:
```sql
SELECT COUNT(opponent) AS _4_when_opponent_was_the_texasan_s = _4_ WHEN Opponent = "The Texasan's" VARCHAR
FROM table_name_37
WHERE week = 4
```

--------------------------------------------------

In [ ]:
# ==========================================
# PHASE 4.4: MERGING WEIGHTS FOR vLLM EXPORT
# ==========================================
import os

print("[INFO] Preparing to merge LoRA adapters into base weights...")

# CRITICAL SAFEGUARD:
# We save this to Colab's LOCAL temporary disk (/content/), NOT Google Drive.
# A fully merged 16-bit 8B model is ~15GB. Saving it to Drive will trigger an "Out of Space" error.
# For Phase 5, vLLM will load it directly from Colab's local high-speed storage!

export_path = "/content/merged_dpo_model"
os.makedirs(export_path, exist_ok=True)

print(f"\n[INFO] Merging model to 16-bit and saving to {export_path}...")
print("(This will take a few minutes. Grab a coffee!)")

# Unsloth's built-in merging engine
model.save_pretrained_merged (
    export_path,
    tokenizer,
    save_method = "merged_16bit", # Perfect format for vLLM deployment
)

print("\n[SUCCESS] PHASE 4 COMPLETE! Your model is merged and ready for Phase 5 (vLLM API Deployment)!")

[INFO] Preparing to merge LoRA adapters into base weights...

[INFO] Merging model to 16-bit and saving to /content/merged_dpo_model...
(This will take a few minutes. Grab a coffee!)

config.json:   0%|          | 0.00/896 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Unsloth: Restored added_tokens_decoder metadata in /content/merged_dpo_model/tokenizer_config.json.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00004.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors: reconstructing file:   0%|          |  0.00B / 4.98GB

model-00001-of-00004.safetensors: downloading bytes:           |  0.00B

Unsloth: Preparing safetensor model files:  25%|██▌       | 1/4 [00:42<02:06, 42.22s/it]

model-00002-of-00004.safetensors: reconstructing file:   0%|          |  0.00B / 5.00GB

model-00002-of-00004.safetensors: downloading bytes:           |  0.00B

Unsloth: Preparing safetensor model files:  50%|█████     | 2/4 [01:28<01:29, 44.85s/it]

model-00003-of-00004.safetensors: reconstructing file:   0%|          |  0.00B / 4.92GB

model-00003-of-00004.safetensors: downloading bytes:           |  0.00B

Unsloth: Preparing safetensor model files:  75%|███████▌  | 3/4 [02:07<00:41, 41.92s/it]

model-00004-of-00004.safetensors: reconstructing file:   0%|          |  0.00B / 1.17GB

model-00004-of-00004.safetensors: downloading bytes:           |  0.00B

Unsloth: Preparing safetensor model files: 100%|██████████| 4/4 [02:14<00:00, 33.61s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit:   0%|          | 0/4 [00:00<?, ?it/s]

Unsloth: Merging weights into 16bit:  25%|██▌       | 1/4 [00:48<02:25, 48.56s/it]

Unsloth: Merging weights into 16bit:  50%|█████     | 2/4 [01:37<01:37, 48.80s/it]

Unsloth: Merging weights into 16bit:  75%|███████▌  | 3/4 [02:28<00:49, 49.84s/it]

Unsloth: Merging weights into 16bit: 100%|██████████| 4/4 [02:35<00:00, 38.79s/it]

Unsloth: Merge process complete. Saved to `/content/merged_dpo_model`

[SUCCESS] PHASE 4 COMPLETE! Your model is merged and ready for Phase 5 (vLLM API Deployment)!

# **Phase 5: vLLM Production Deployment & API Tunneling**
Booting a headless OpenAI-compatible API server using vLLM and PagedAttention. Mitigating CUDA Graph Deadlocks and OOM crashes with Eager Execution and on-the-fly 4-bit inference, then exposing the local port to the public web via an Ngrok HTTPS tunnel.

In [ ]:
# ==========================================
# PHASE 5.1: PRODUCTION STACK INSTALLATION
# ==========================================

print("[INFO] Installing vLLM (High-Throughput Serving Engine)...")
# Installing vLLM brings in the custom PagedAttention CUDA kernels.
!pip install vllm

print("\n[INFO] Installing PyNgrok (Secure Tunneling)...")
# PyNgrok is the Python wrapper that lets us control Ngrok directly from our script.
!pip install pyngrok

print("\n[SUCCESS] Phase 5.1 Complete! Production stack is installed.")

[INFO] Installing vLLM (High-Throughput Serving Engine)...
Collecting vllm
  Downloading vllm-0.27.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm) (5.9.5)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm) (2.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm) (4.67.3)
Collecting blake3 (from vllm)
  Downloading blake3-1.0.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers>=5.5.3 (from vllm)
  Downloading transformers-5.15.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)
Requirement already satisfied: safetensors>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.0)
Requirement already satisfied: protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.29.6)
Collecting fastapi<0.137.0,>=0.133.0 (from fastapi[standard]<0.137.0,>=0.133.0->vllm)
  Downloading fastapi-0.136.3-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: starlette>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.3.1)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.14.1)
Requirement already satisfied: openai>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.45.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.13.4)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Collecting prometheus-fastapi-instrumentator>=8.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-8.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.13.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.8.0,>=1.7.0 (from vllm)
  Downloading llguidance-1.7.6-cp39-abi3-manylinux_2_31_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.14 (from vllm)
  Downloading outlines_core-0.2.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar<1.0.0,>=0.2.1 (from vllm)
  Downloading xgrammar-0.2.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.16.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.29.7)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.26.0)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from vllm) (0.21.1)
Collecting mistral_common>=1.11.6 (from mistral_common[image]>=1.11.6->vllm)
  Downloading mistral_common-1.11.7-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (5.0.0.93)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Collecting compressed-tensors==0.17.0 (from vllm)
  Downloading compressed_tensors-0.17.0-py3-none-any.whl.metadata (4.7 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.2.0)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.1.0)
Collecting ninja (from vllm)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.5.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (11 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-6.1.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-0.122.0-py3-none-any.whl.metadata (3.3 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.14 (from vllm)
  Downloading model_hosting_container_standards-0.1.16-py3-none-any.whl.metadata (24 kB)
Collecting mcp (from vllm)
  Downloading mcp-2.0.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.42.1)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.42.1)
Collecting opentelemetry-exporter-otlp>=1.27.0 (from vllm)
  Downloading opentelemetry_exporter_otlp-1.44.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions-ai>=0.4.1 (from vllm)
  Downloading opentelemetry_semantic_conventions_ai-0.5.1-py3-none-any.whl.metadata (997 bytes)
Collecting numba==0.65.0 (from vllm)
  Downloading numba-0.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting torch==2.13.0 (from vllm)
  Downloading torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
Requirement already satisfied: torchaudio==2.11.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.11.0+cu128)
Collecting torchvision==0.28.0 (from vllm)
  Downloading torchvision-0.28.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Collecting torchcodec>=0.14 (from vllm)
  Downloading torchcodec-0.16.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.7 kB)
Collecting PyNvVideoCodec==2.0.4 (from vllm)
  Downloading pynvvideocodec-2.0.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting flashinfer-python==0.6.16.post3 (from vllm)
  Downloading flashinfer_python-0.6.16.post3-py3-none-any.whl.metadata (11 kB)
Collecting apache-tvm-ffi==0.1.11 (from vllm)
  Downloading apache_tvm_ffi-0.1.11-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting tilelang==0.1.12 (from vllm)
  Downloading tilelang-0.1.12-cp38-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Collecting nvidia-cudnn-frontend>=1.19.1 (from vllm)
  Downloading nvidia_cudnn_frontend-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Requirement already satisfied: nvtx==0.2.15 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.15)
Collecting fastsafetensors>=0.3.2 (from vllm)
  Downloading fastsafetensors-0.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting nvidia-cutlass-dsl==4.6.0 (from nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cutlass_dsl-4.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting quack-kernels==0.6.1 (from vllm)
  Downloading quack_kernels-0.6.1-py3-none-any.whl.metadata (800 bytes)
Collecting tokenspeed-mla==0.1.8 (from vllm)
  Downloading tokenspeed_mla-0.1.8-py3-none-manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting humming-kernels==0.1.10 (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading humming_kernels-0.1.10-py3-none-any.whl.metadata (4.1 kB)
Collecting loguru (from compressed-tensors==0.17.0->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.3.8)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (8.4.2)
Requirement already satisfied: cuda-python>=12.0 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (12.9.7)
Collecting cuda-tile>=1.4.0 (from flashinfer-python==0.6.16.post3->vllm)
  Downloading cuda_tile-1.5.0-cp312-cp312-manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting nccl4py>=0.3.1 (from flashinfer-python==0.6.16.post3->vllm)
  Downloading nccl4py-0.4.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (13.610.43)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (26.2)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (0.9.0)
Requirement already satisfied: triton in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm) (3.6.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm) (3.1.6)
Collecting pyelftools (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm)
  Downloading pyelftools-0.33-py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: cuda-bindings in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm) (12.9.7)
Collecting nvidia-cuda-runtime (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_runtime-13.3.29-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-cccl (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_cccl-13.3.3.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvcc (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_nvcc-13.3.73-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cuda-nvrtc (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_nvrtc-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.48,>=0.47.0dev0 (from numba==0.65.0->vllm)
  Downloading llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting nvidia-cutlass-dsl-libs-base==4.6.0 (from nvidia-cutlass-dsl==4.6.0->nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cutlass_dsl_libs_base-4.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting nvidia-cutlass-dsl-libs-cu12==4.6.0 (from nvidia-cutlass-dsl==4.6.0->nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cutlass_dsl_libs_cu12-4.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting nvidia-cutlass-dsl-libs-cu13==4.6.0 (from nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cutlass_dsl_libs_cu13-4.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting torch-c-dlpack-ext (from quack-kernels==0.6.1->vllm)
  Downloading torch_c_dlpack_ext-0.1.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.12->vllm) (0.5.4)
Collecting z3-solver<4.15.5,>=4.13.0 (from tilelang==0.1.12->vllm)
  Downloading z3_solver-4.15.4.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (602 bytes)
Collecting tokenspeed-triton>=3.7.10.post20260531 (from tokenspeed-mla==0.1.8->vllm)
  Downloading tokenspeed_triton-3.8.10.post20260721-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (3.6.1)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (2025.3.0)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm)
  Downloading cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch==2.13.0->vllm)
  Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch==2.13.0->vllm)
  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch==2.13.0->vllm)
  Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch==2.13.0->vllm)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm)
  Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime (from humming-kernels[cu13]==0.1.10->vllm)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 (from vllm)
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting nvidia-cuda-nvdisasm<14,>=13.3 (from nvidia-cutlass-dsl-libs-base==4.6.0->nvidia-cutlass-dsl==4.6.0->nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cuda_nvdisasm-13.3.73-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cutlass-dsl-libs-core==4.6.0 (from nvidia-cutlass-dsl-libs-base==4.6.0->nvidia-cutlass-dsl==4.6.0->nvidia-cutlass-dsl[cu13]==4.6.0->vllm)
  Downloading nvidia_cutlass_dsl_libs_core-4.6.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (0.5.2)

[INFO] Installing PyNgrok (Secure Tunneling)...
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

[SUCCESS] Phase 5.1 Complete! Production stack is installed.

In [ ]:
!pip uninstall torchaudio torchvision -y

Found existing installation: torchaudio 2.11.0+cu128
Uninstalling torchaudio-2.11.0+cu128:
  Successfully uninstalled torchaudio-2.11.0+cu128
Found existing installation: torchvision 0.28.0
Uninstalling torchvision-0.28.0:
  Successfully uninstalled torchvision-0.28.0

In [ ]:
!pip install torchvision

Collecting torchvision
  Using cached torchvision-0.28.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: torch==2.13.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.13.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (2025.3.0)
Requirement already satisfied: cuda-toolkit==13.0.3 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->torchvision) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->torchvision) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<14,>=13.0.3->torch==2.13.0->torchvision) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.13.0->torchvision) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.13.0->torchvision) (3.0.3)
Using cached torchvision-0.28.0-cp312-cp312-manylinux_2_28_x86_64.whl (7.7 MB)
Installing collected packages: torchvision
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vllm 0.27.1 requires torchaudio==2.11.0, which is not installed.
Successfully installed torchvision-0.28.0

In [ ]:
# ==========================================
# PHASE 5.2: BOOTING THE vLLM API SERVER
# ==========================================
import subprocess
import time
import requests
import torch
import gc
import sys
import os

print("[INFO] Step 1: Assassinating frozen background processes...")
# This Linux command forcefully kills any running vLLM server
os.system("pkill -9 -f api_server")
time.sleep(2)

print("[INFO] Step 1: Flushing PyTorch VRAM to make room for vLLM...")
# NECESSARY OOM SAFEGUARD: We must delete the Phase 4 Unsloth model from memory!
if 'model' in locals():
    del model
if 'tokenizer' in locals():
    del tokenizer
gc.collect()
torch.cuda.empty_cache()
print(f"VRAM Cleared. Currently Allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

print("\n[INFO] Step 2: Booting up vLLM OpenAI-Compatible Server in the background...")
print("[INFO] This will take about 2-3 minutes. It is loading 16GB of weights into VRAM.")

# We route the server logs to a text file so it doesn't clutter our notebook UI
log_file = open("vllm_server.log", "w")

# The command to launch vLLM as an OpenAI-compatible API
vllm_command = [
    sys.executable, "-m", "vllm.entrypoints.openai.api_server",
    "--model", "/content/merged_dpo_model", # Pointing directly to your Phase 4 output!
    "--max-model-len", "2048",              # Restricting max context to save VRAM
    "--gpu-memory-utilization", "0.85",     # Letting vLLM consume 85% of total VRAM
    "--port", "8000",                     # Standard local API port
    "--enforce-eager",               # Fixes the CUDA Graph Deadlock freeze!
    "--quantization", "bitsandbytes"     # Fixes the Out  of Memory crash
]

# Launch as a background process!
vllm_process = subprocess.Popen(vllm_command, stdout=log_file, stderr=subprocess.STDOUT)

[INFO] Step 1: Assassinating frozen background processes...
[INFO] Step 1: Flushing PyTorch VRAM to make room for vLLM...
VRAM Cleared. Currently Allocated: 0.00 GB

[INFO] Step 2: Booting up vLLM OpenAI-Compatible Server in the background...
[INFO] This will take about 2-3 minutes. It is loading 16GB of weights into VRAM.

In [ ]:
# Wait for the server to initialize
print("\n[INFO] Step 3: Waiting for server to hit 'Ready' state (checking localhost:8000)...")
server_ready = False
# We ping the server every 10 seconds. When it responds with 200 OK, we know it's alive!
for i in range(30):
    try:
        response = requests.get("http://localhost:8000/v1/models")
        if response.status_code == 200 :
            print("\n[SUCCESS] vLLM Server is ONLINE and actively listening on Port 8000!")
            server_ready = True
            break
    except requests.exceptions.ConnectionError:
        time.sleep(10)
        print(f"Waiting... ({i*10} seconds elapsed)")

if not server_ready:
    print("\n[ERROR] Server failed to start. Check the 'vllm_server.log' file for details.")

[INFO] Step 3: Waiting for server to hit 'Ready' state (checking localhost:8000)...

[SUCCESS] vLLM Server is ONLINE and actively listening on Port 8000!

In [ ]:
# ==========================================
# PHASE 5.3: ESTABLISH NGROK TUNNEL
# ==========================================
from pyngrok import ngrok, conf
import getpass

print("=== NGROK AUTHENTICATION ===")
print("Please enter your Ngrok Authtoken (from dashboard.ngrok.com):")
# getpass hides your token so it doesn't show up in the notebook output!
ngrok_token = getpass.getpass()

# Configure Ngrok with your token
conf.get_default().auth_token = ngrok_token

print("\n[INFO] Drilling secure tunnel through Google's firewall...")
# We tell Ngrok to hook into localhost port 8000 (where vLLM is listening)
public_url = ngrok.connect(8000).public_url

print(f"\n[SUCCESS] TUNNEL ESTABLISHED!")
print(f" YOUR SECURE PUBLIC API URL: {public_url}")

=== NGROK AUTHENTICATION ===
Please enter your Ngrok Authtoken (from dashboard.ngrok.com):
··········

[INFO] Drilling secure tunnel through Google's firewall...

[SUCCESS] TUNNEL ESTABLISHED!
 YOUR SECURE PUBLIC API URL: https://caroll-benefic-gabriele.ngrok-free.dev

In [ ]:
# ==========================================
# PHASE 5.4: THE FINAL PRODUCTION API PING
# ==========================================
import requests
import json

print(f"[INFO] Transmitting API Request to {public_url}...\n")

# The OpenAI-Compatible Endpoint route
api_endpoint = f"{public_url}/v1/chat/completions"

# A  new Enterprise Schema and Question
test_schema = """
CREATE TABLE corporate_assets (
    asset_id INT PRIMARY KEY,
    asset_name VARCHAR(100),
    purchase_cost DECIMAL(12, 2),
    department_owner VARCHAR(50)
);
"""
test_question = "List all assets owned by the Marketing department that cost more than 10000, sorted by highest cost."

# The JSON Payload
# This looks EXACTLY like a standard OpenAI ChatGPT API call.
payload = {
    "model": "/content/merged_dpo_model", # vLLM uses the folder path as the model name.
    "messages": [
        {
            "role": "system",
            "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."
        },
        {
            "role": "user",
            "content": f"Database Schema:\n{test_schema}\n\nQuestion:\n{test_question}"
        }
    ],
    "temperature": 0.0,  # Strict determinism
    "max_tokens": 256
}

headers = {
    "Content-Type": "application/json"
}

# Fire the POST request!
response = requests.post(api_endpoint, json=payload, headers=headers)

if response.status_code == 200:
    result = response.json()
    # Extracting the assistant's reply from the standard OpenAI JSON structure
    generated_sql = result["choices"][0]["message"]["content"]

    print("==========================================")
    print("ENTERPRISE SQL API RESPONSE")
    print("==========================================")
    print(generated_sql)
else:
    print(f"[ERROR] API failed with status {response.status_code}")
    print(response.text)

[INFO] Transmitting API Request to https://caroll-benefic-gabriele.ngrok-free.dev...

==========================================
ENTERPRISE SQL API RESPONSE
==========================================
```sql
SELECT MAX(purchase_cost) AS max_cost, asset_name, department_owner
FROM corporate_assets
WHERE department_owner = "Marketing" AND purchase_cost > 10000
GROUP BY asset_name, department_owner
```

# **"Live Interview Demo"**

In [1]:
# ==========================================
# INTERVIEW LIVE DEMO SCRIPT
# ==========================================

# 1. Install bare minimum requirements
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes

# 2. Mount your "Cloud Storage" (Google Drive)
from google.colab import drive
drive.mount('/content/drive')

from unsloth import FastLanguageModel
import torch

# 3. Load the DPO Adapters directly from Drive
print("\n[INFO] Loading fine-tuned DPO model...")
project_path = '/content/drive/MyDrive/Enterprise_SQL_LLM'
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = f"{project_path}/lora_dpo_final_model",
    max_seq_length = 2048,
    load_in_4bit = True, # 4-bit quantization prevents OOM
)
FastLanguageModel.for_inference(model) # Enable 2x faster inference

# 4. Define a Live Test Case
test_schema = """
CREATE TABLE server_logs (
    log_id INT,
    cpu_utilization FLOAT,
    timestamp DATETIME
);
"""
test_question = "Find the timestamp of the absolute lowest cpu utilization recorded."

messages = [
    {"role": "system", "content": "You are an expert SQL assistant. Your only job is to write exact, valid SQL queries based strictly on the provided database schema. Do not explain the query or include conversational filler. Return only the SQL query inside a markdown code block."},
    {"role": "user", "content": f"Database Schema:\n{test_schema}\n\nQuestion:\n{test_question}"}
]

# 5. Generate and Print
print("\n[INFO] Generating SQL...")
prompt = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_dict=True, return_tensors="pt").to("cuda")
outputs = model.generate(**prompt, max_new_tokens=256, use_cache=True, max_length=None, do_sample=False)
print("\n" + "="*40 + "\n MODEL RESPONSE \n" + "="*40)
print(tokenizer.decode(outputs[0][prompt["input_ids"].shape[1]:], skip_special_tokens=True))

Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-926gf8uu/unsloth_607f3309f8ba43c7b8ce8b71eeef00a4
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-926gf8uu/unsloth_607f3309f8ba43c7b8ce8b71eeef00a4
  Resolved https://github.com/unslothai/unsloth.git to commit bfcaea46574d63ec470ce9c7d7221471a38ea7e4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.26.8)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting structlog>=24.1.0 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading structlog-26.1.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (8.4.2)
Collecting unsloth_zoo>=2026.8.12 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.8.12-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (26.2)
Collecting tyro (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.15-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.23.0)
Collecting hf_transfer (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.50.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.6.0)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-25.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.16.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.20.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.19.1)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.8.12->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.16.3)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.5.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.9.7)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load /content/drive/MyDrive/Enterprise_SQL_LLM/lora_dpo_final_model as a legacy tokenizer.
Unsloth 2026.8.18 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

[INFO] Generating SQL...

========================================
 MODEL RESPONSE
========================================
```sql
SELECT MIN(timestamp) AS timestamp
FROM server_logs
WHERE cpu_utilization = (SELECT MIN(cpu_utilization) FROM server_logs)
```